## This content is duplicated here from configs/config_designers.yml because I'm building this site through Github Pages, and Github Pages just looks for the _config.yml file in the root directory to create the build.
# project definitions
project: doc_designers
audience: designers
product: all
platform: all
version: all
destination: ../doc_designers
topnav_title: Jekyll Documentation Theme
homepage_title: Jekyll Documentation Theme &mdash; Designers
site_title: Jekyll Documentation Theme &mdash; Designers
disqus_shortname: idrbwjekyll
google_analytics: UA-66296557-1
github_editme_path: tomjohnson1492/documentation-theme-jekyll/blob/gh-pages
# don't use a slash before or after the above path. here's how this url gets written out in page.html: https://github.com/{{site.github_editme_path}}{{page.url | replace: '.html', '.md'}}
# variables

sidebar_tagline: designers
sidebar_version: version 3.0
comments: true

port: 4001

exclude:
  - doc_writers*
  - configs/
  - _site
  - doc_multi*

# same for all
host: 127.0.0.1
feedback_email: tomjohnson1492@gmail.com
sidebar_accordion: true
markdown: redcarpet
print: false
theme_file: theme-blue.css
# only use suffix if you need to force index.html to display
# suffix: index.html

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: pygments

collections:
  tooltips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      
      <div id="disqus_thread"></div>
<script>


var disqus_config = function () {
this.page.url = '{{content.abolute_url}}';  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '{{content_id}}'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://act-network.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            
